#####################################
# swarm에서 작동하는 docker-compose
#####################################
version: '3.8'

########################### SERVICES
services:
  wordpress:
    image: ghcr.io/hansanghyeon/wordpress-redis
    restart: always
    environment:
      WORDPRESS_DB_HOST: DB_mariadb:3306
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}_dev
      WORDPRESS_CONFIG_EXTRA: |
        /* Redis */
        define('WP_REDIS_HOST', getenv_docker('WORDPRESS_REDIS_HOST', 'TOY-hyeon-dev_redis'));
        define('WP_REDIS_PORT', getenv_docker('WORDPRESS_REDIS_PORT', 6379));
        define( 'WP_ENVIRONMENT_TYPE', 'local' );
        define( 'NIUI_HOST', 'https://dev.hyeon.pro');
    volumes:
      - wordpress:/var/www/html
      - ./dev:/var/www/html/wp-content/themes/sage
    deploy:
      placement:
        constraints:
          - node.hostname == ${HOSTNAME}
      labels:
        - traefik.enable=true
        ## HTTP Routers
        - traefik.http.routers.hyeon_dev.entrypoints=websecure
        - traefik.http.routers.hyeon_dev.rule=Host(`dev.hyeon.pro`)
        - traefik.http.routers.hyeon_dev.tls.certresolver=leresolver
        - traefik.http.services.hyeon_dev.loadbalancer.server.port=80
  redis:
    image: redis:latest
    volumes:
      - redis:/data
    deploy:
      placement:
        constraints:
          - node.hostname == ${HOSTNAME}

########################### NETWORKS
networks:
  default:
    external:
      name: DB_net
volumes:
  redis:
  wordpress:
